### PR TITLE
Make `EcoVec::extend_from_trusted` public

### PR DESCRIPTION
**Pull request by kaikalii**
Add the bound `I::IntoIter: ExactSizeIterator` to try to prevent unsafe usage.

I need this so I can do no-`Clone` extension without the overhead of the safe `Extend::extend` implementation referenced in #38.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Unfortunate that `TrustedLen` is unstable. I wonder whether we should keep `count` in the method signature though or whether we should rather use the `len()` method of `ExactSizeIterator`?

**Comment by kaikalii** [comment]
I think that makes more sense. Updated.

**Comment by laurmaedje** [comment]
Thanks! Do you want a release?

**Comment by kaikalii** [comment]
That would be great.

**Comment by laurmaedje** [comment]
Done.

**Pull request merged**
